<?php
$country_list = [
    ['name' => '中国', 'code' => 'CN'],
    ['name' => '香港', 'code' => 'HK'],
    ['name' => '澳门', 'code' => 'MO'],
    ['name' => '蒙古', 'code' => 'MN'],
    ['name' => '朝鲜', 'code' => 'KP'],
    ['name' => '韩国', 'code' => 'KR'],
    ['name' => '日本', 'code' => 'JP'],

    // 东南亚
    ['name' => '菲律宾', 'code' => 'PH'],
    ['name' => '越南', 'code' => 'VN'],
    ['name' => '老挝', 'code' => 'LA'],
    ['name' => '柬埔寨', 'code' => 'KH'],
    ['name' => '缅甸', 'code' => 'MM'],
    ['name' => '泰国', 'code' => 'TH'],
    ['name' => '马来西亚', 'code' => 'MY'],
    ['name' => '文莱', 'code' => 'BN'],
    ['name' => '新加坡', 'code' => 'SG'],
    ['name' => '印度尼西亚', 'code' => 'ID'],
    ['name' => '东帝汶', 'code' => 'TL'],

    // 南亚
    ['name' => '尼泊尔', 'code' => 'NP'],
    ['name' => '不丹', 'code' => 'BT'],
    ['name' => '孟加拉国', 'code' => 'BD'],
    ['name' => '印度', 'code' => 'IN'],
    ['name' => '巴基斯坦', 'code' => 'PK'],
    ['name' => '斯里兰卡', 'code' => 'LK'],
    ['name' => '马尔代夫', 'code' => 'MV'],

    // 中亚
    ['name' => '哈萨克斯坦', 'code' => 'KZ'],
    ['name' => '吉尔吉斯斯坦', 'code' => 'KG'],
    ['name' => '塔吉克斯坦', 'code' => 'TJ'],
    ['name' => '乌兹别克斯坦', 'code' => 'UZ'],
    ['name' => '土库曼斯坦', 'code' => 'TM'],

    // 西亚
    ['name' => '阿富汗', 'code' => 'AF'],
    ['name' => '伊拉克', 'code' => 'IQ'],
    ['name' => '伊朗', 'code' => 'IR'],
    ['name' => '叙利亚', 'code' => 'SY'],
    ['name' => '约旦', 'code' => 'JO'],
    ['name' => '黎巴嫩', 'code' => 'LB'],
    ['name' => '以色列', 'code' => 'IL'],
    ['name' => '巴勒斯坦', 'code' => 'PS'],
    ['name' => '沙特阿拉伯', 'code' => 'SA'],
    ['name' => '巴林', 'code' => 'BH'],
    ['name' => '卡塔尔', 'code' => 'QA'],
    ['name' => '科威特', 'code' => 'KW'],
    ['name' => '阿联酋', 'code' => 'AE'],
    ['name' => '阿曼', 'code' => 'OM'],
    ['name' => '也门', 'code' => 'YE'],
    ['name' => '格鲁吉亚', 'code' => 'GE'],
    ['name' => '亚美尼亚', 'code' => 'AM'],
    ['name' => '阿塞拜疆', 'code' => 'AZ'],
    ['name' => '土耳其', 'code' => 'TR'],
    ['name' => '塞浦路斯', 'code' => 'CY'],

    // 欧洲
    // 北欧
    ['name' => '芬兰', 'code' => 'FI'],
    ['name' => '瑞典', 'code' => 'SE'],
    ['name' => '挪威', 'code' => 'NO'],
    ['name' => '冰岛', 'code' => 'IS'],
    ['name' => '丹麦', 'code' => 'DK'],
    ['name' => '法罗群岛', 'code' => 'FO'],

    // 东欧
    ['name' => '爱沙尼亚', 'code' => 'EE'],
    ['name' => '拉脱维亚', 'code' => 'LV'],
    ['name' => '立陶宛', 'code' => 'LT'],
    ['name' => '白俄罗斯', 'code' => 'BY'],
    ['name' => '俄罗斯', 'code' => 'RU'],
    ['name' => '乌克兰', 'code' => 'UA'],
    ['name' => '摩尔多瓦', 'code' => 'MD'],

    // 中欧
    ['name' => '波兰', 'code' => 'PL'],
    ['name' => '捷克', 'code' => 'CZ'],
    ['name' => '斯洛伐克', 'code' => 'SK'],
    ['name' => '匈牙利', 'code' => 'HU'],
    ['name' => '德国', 'code' => 'DE'],
    ['name' => '奥地利', 'code' => 'AT'],
    ['name' => '瑞士', 'code' => 'CH'],
    ['name' => '列支敦士登', 'code' => 'LI'],

    // 西欧
    ['name' => '英国', 'code' => 'GB'],
    ['name' => '爱尔兰', 'code' => 'IE'],
    ['name' => '荷兰', 'code' => 'NL'],
    ['name' => '比利时', 'code' => 'BE'],
    ['name' => '卢森堡', 'code' => 'LU'],
    ['name' => '法国', 'code' => 'FR'],
    ['name' => '摩纳哥', 'code' => 'MC'],

    // 南欧
    ['name' => '罗马尼亚', 'code' => 'RO'],
    ['name' => '保加利亚', 'code' => 'BG'],
    ['name' => '塞尔维亚', 'code' => 'RS'],
    ['name' => '马其顿', 'code' => 'MK'],
    ['name' => '阿尔巴尼亚', 'code' => 'AL'],
    ['name' => '希腊', 'code' => 'GR'],
    ['name' => '斯洛文尼亚', 'code' => 'SI'],
    ['name' => '克罗地亚', 'code' => 'HR'],
    ['name' => '波斯尼亚', 'code' => 'BA'],
    ['name' => '意大利', 'code' => 'IT'],
    ['name' => '梵蒂冈', 'code' => 'VA'],
    ['name' => '圣马力诺', 'code' => 'SM'],
    ['name' => '马耳他', 'code' => 'MT'],
    ['name' => '西班牙', 'code' => 'ES'],
    ['name' => '葡萄牙', 'code' => 'PT'],
    ['name' => '安道尔', 'code' => 'AD'],

    // 非洲
    // 北非
    ['name' => '埃及', 'code' => 'EG'],
    ['name' => '利比亚', 'code' => 'LY'],
    ['name' => '苏丹', 'code' => 'SD'],
    ['name' => '突尼斯', 'code' => 'TN'],
    ['name' => '阿尔及利亚', 'code' => 'DZ'],
    ['name' => '摩洛哥', 'code' => 'MA'],

    // 东非
    ['name' => '埃塞俄比亚', 'code' => 'ET'],
    ['name' => '厄立特里亚', 'code' => 'ER'],
    ['name' => '索马里', 'code' => 'SO'],
    ['name' => '吉布提', 'code' => 'DJ'],
    ['name' => '肯尼亚', 'code' => 'KE'],
    ['name' => '坦桑尼亚', 'code' => 'TZ'],
    ['name' => '乌干达', 'code' => 'UG'],
    ['name' => '卢旺达', 'code' => 'RW'],
    ['name' => '布隆迪', 'code' => 'BI'],
    ['name' => '塞舌尔', 'code' => 'SC'],
    //中非
    ['name' => '乍得', 'code' => 'TD'],
    ['name' => '中非', 'code' => 'CF'],
    ['name' => '喀麦隆', 'code' => 'CM'],
    ['name' => '赤道几内亚', 'code' => 'GQ'],
    ['name' => '加蓬', 'code' => 'GA'],
    ['name' => '刚果共和国', 'code' => 'CG'],
    ['name' => '刚果民主共和国', 'code' => 'CD'],
    ['name' => '圣多美及普林西比', 'code' => 'ST'],

    // 西非
    ['name' => '毛里塔尼亚', 'code' => 'MR'],
    ['name' => '西撒哈拉', 'code' => 'EH'],
    ['name' => '塞内加尔', 'code' => 'SN'],
    ['name' => '冈比亚', 'code' => 'GM'],
    ['name' => '马里', 'code' => 'ML'],
    ['name' => '布基纳法索', 'code' => 'BF'],
    ['name' => '几内亚', 'code' => 'GN'],
    ['name' => '几内亚比绍', 'code' => 'GW'],
    ['name' => '佛得角', 'code' => 'CV'],
    ['name' => '塞拉利昂', 'code' => 'SL'],
    ['name' => '利比里亚', 'code' => 'LR'],
    ['name' => '科特迪瓦', 'code' => 'CI'],
    ['name' => '加纳', 'code' => 'GH'],
    ['name' => '多哥', 'code' => 'TG'],
    ['name' => '贝宁', 'code' => 'BJ'],
    ['name' => '尼日尔', 'code' => 'NE'],
    ['name' => '加那利群岛', 'code' => 'IC'],

    // 南非
    ['name' => '赞比亚', 'code' => 'ZM'],
    ['name' => '安哥拉', 'code' => 'AO'],
    ['name' => '津巴布韦', 'code' => 'ZW'],
    ['name' => '马拉维', 'code' => 'MW'],
    ['name' => '莫桑比克', 'code' => 'MZ'],
    ['name' => '博茨瓦纳', 'code' => 'BW'],
    ['name' => '纳米比亚', 'code' => 'NA'],
    ['name' => '南非', 'code' => 'ZA'],
    ['name' => '斯威士兰', 'code' => 'SZ'],
    ['name' => '莱索托', 'code' => 'LS'],
    ['name' => '马达加斯加', 'code' => 'MG'],
    ['name' => '科摩罗', 'code' => 'KM'],
    ['name' => '毛里求斯', 'code' => 'MU'],
    ['name' => '留尼旺', 'code' => 'RE'],
    ['name' => '圣赫勒拿', 'code' => 'SH'],
    // 大洋洲
    ['name' => '澳大利亚', 'code' => 'AU'],
    ['name' => '新西兰', 'code' => 'NZ'],
    ['name' => '巴布亚新几内亚', 'code' => 'PG'],
    ['name' => '所罗门群岛', 'code' => 'SB'],
    ['name' => '瓦努阿图', 'code' => 'VU'],
    ['name' => '密克罗尼西亚', 'code' => 'FM'],
    ['name' => '马绍尔群岛', 'code' => 'MH'],
    ['name' => '帕劳', 'code' => 'PW'],
    ['name' => '瑙鲁', 'code' => 'NR'],
    ['name' => '基里巴斯', 'code' => 'KI'],
    ['name' => '图瓦卢', 'code' => 'TV'],
    ['name' => '萨摩亚', 'code' => 'WS'],
    ['name' => '斐济群岛', 'code' => 'FJ'],
    ['name' => '汤加', 'code' => 'TO'],
    ['name' => '库克群岛', 'code' => 'CK'],
    ['name' => '关岛', 'code' => 'GU'],
    ['name' => '新喀里多尼亚', 'code' => 'NC'],
    ['name' => '法属波利尼西亚', 'code' => 'PF'],
    ['name' => '皮特凯恩岛', 'code' => 'PN'],
    ['name' => '瓦利斯与富图纳', 'code' => 'WF'],
    ['name' => '纽埃', 'code' => 'NU'],
    ['name' => '托克劳', 'code' => 'TK'],
    ['name' => '美属萨摩亚', 'code' => 'AS'],
    ['name' => '北马里亚纳', 'code' => 'MP'],
    // 北美洲
    ['name' => '加拿大', 'code' => 'CA'],
    ['name' => '美国', 'code' => 'US'],
    ['name' => '墨西哥', 'code' => 'MX'],
    ['name' => '格陵兰', 'code' => 'GL'],

    // 中美洲
    ['name' => '危地马拉', 'code' => 'GT'],
    ['name' => '伯利兹', 'code' => 'BZ'],
    ['name' => '萨尔瓦多', 'code' => 'SV'],
    ['name' => '洪都拉斯', 'code' => 'HN'],
    ['name' => '尼加拉瓜', 'code' => 'NI'],
    ['name' => '哥斯达黎加', 'code' => 'CR'],
    ['name' => '巴拿马', 'code' => 'PA'],
    // 加勒比海地区
    ['name' => '巴哈马', 'code' => 'BS'],
    ['name' => '古巴', 'code' => 'CU'],
    ['name' => '牙买加', 'code' => 'JM'],
    ['name' => '海地', 'code' => 'HT'],
    ['name' => '多米尼加共和国', 'code' => 'DO'],
    ['name' => '安提瓜和巴布达', 'code' => 'AG'],
    ['name' => '圣基茨和尼维斯', 'code' => 'KN'],
    ['name' => '多米尼克', 'code' => 'DM'],
    ['name' => '圣卢西亚', 'code' => 'LC'],
    ['name' => '圣文森特和格林纳丁斯', 'code' => 'VC'],
    ['name' => '格林纳达', 'code' => 'GD'],
    ['name' => '巴巴多斯', 'code' => 'BB'],
    ['name' => '特立尼达和多巴哥', 'code' => 'TT'],
    ['name' => '波多黎各', 'code' => 'PR'],
    ['name' => '英属维尔京群岛', 'code' => 'VG'],
    ['name' => '美属维尔京群岛', 'code' => 'VI'],
    ['name' => '安圭拉', 'code' => 'AI'],
    ['name' => '蒙特塞拉特', 'code' => 'MS'],
    ['name' => '瓜德罗普', 'code' => 'GP'],
    ['name' => '马提尼克', 'code' => 'MQ'],
    ['name' => '荷属安的列斯', 'code' => 'AN'],
    ['name' => '阿鲁巴', 'code' => 'AW'],
    ['name' => '特克斯和凯科斯群岛', 'code' => 'TC'],
    ['name' => '开曼群岛', 'code' => 'KY'],
    ['name' => '百慕大', 'code' => 'BM'],
    // 南美洲
    // 哥伦比亚、委内瑞拉等...
    ['name' => '哥伦比亚', 'code' => 'CO'],
    ['name' => '委内瑞拉', 'code' => 'VE'],
    ['name' => '圭亚那', 'code' => 'GY'],
    ['name' => '法属圭亚那', 'code' => 'GF'],
    ['name' => '苏里南', 'code' => 'SR'],
    ['name' => '厄瓜多尔', 'code' => 'EC'],
    ['name' => '秘鲁', 'code' => 'PE'],
    ['name' => '玻利维亚', 'code' => 'BO'],
    ['name' => '巴西', 'code' => 'BR'],
    ['name' => '智利', 'code' => 'CL'],
    ['name' => '阿根廷', 'code' => 'AR'],
    ['name' => '乌拉圭', 'code' => 'UY'],
    ['name' => '巴拉圭', 'code' => 'PY'],
];

// 返回 JSON 格式的国家列表
echo json_encode($country_list);
?>
